# Generated by Django 5.2.4 on 2025-07-04 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileProcess',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('s3_location', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Downloaded', 'Downloaded'), ('Uploaded', 'Uploaded'), ('Queued', 'Queued'), ('Processing', 'Processing'), ('Processed', 'Processed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'File Process',
                'verbose_name_plural': 'File Processes',
                'db_table': 'file_processes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('json_payload', models.JSONField()),
                ('api_status', models.IntegerField()),
                ('api_response', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_process', models.ForeignKey(db_column='unique_id', on_delete=django.db.models.deletion.CASCADE, related_name='api_calls', to='core.fileprocess')),
                ('unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fileprocess')),
            ],
            options={
                'verbose_name': 'API Call',
                'verbose_name_plural': 'API Calls',
                'db_table': 'api_calls',
                'ordering': ['-created_at'],
                'unique_together': {('unique_id', 'row_number')},
            },
        ),
    ]
