# Generated by Django 5.2.4 on 2025-07-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apicall',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='apicall',
            name='row_number',
        ),
        migrations.RemoveField(
            model_name='apicall',
            name='unique_id',
        ),
    ]
