# Generated by Django 5.2.4 on 2025-07-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_apicall_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprocess',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
