# Generated by Django 5.2.4 on 2025-08-11 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailconfig_rename_s3_location_fileprocess_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='A descriptive name for these credentials', max_length=255)),
                ('credential_type', models.CharField(choices=[('ftp', 'FTP'), ('sftp', 'SFTP'), ('api', 'API'), ('database', 'Database'), ('aws', 'AWS'), ('azure', 'Azure'), ('other', 'Other')], default='other', max_length=20)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=500, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('database_name', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_string', models.TextField(blank=True, null=True)),
                ('additional_config', models.JSONField(blank=True, help_text='Additional configuration as JSON', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'db_table': 'credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_credentials', to='core.credentials')),
            ],
            options={
                'verbose_name': 'Site Credential',
                'verbose_name_plural': 'Site Credentials',
                'db_table': 'site_credentials',
                'ordering': ['-created_at'],
                'unique_together': {('credentials', 'site_id')},
            },
        ),
    ]
