# Generated by Django 5.2.4 on 2025-08-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_credentials_sitecredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='connection_string',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='database_name',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='host',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='port',
        ),
        migrations.AddField(
            model_name='credentials',
            name='certificate',
            field=models.FileField(blank=True, help_text='Upload a certificate file if required', null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='credential_type',
            field=models.CharField(choices=[('api', 'API'), ('api-certificate', 'API-CERTIFICATE')], default='other', max_length=20),
        ),
    ]
