# Generated by Django 5.2.6 on 2025-09-18 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_credentials_connection_string_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BNSFCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client_pfx', models.FileField(upload_to='certificates/')),
                ('server_cer', models.FileField(upload_to='certificates/')),
                ('pfx_password', models.CharField(max_length=100)),
                ('api_url', models.URLField(default='https://api-trial.bnsf.com:6443/v1/cars')),
                ('skip_verify', models.BooleanField(default=False)),
                ('site_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BNSF Certificate',
                'verbose_name_plural': 'BNSF Certificates',
                'db_table': 'bnsf_certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BNSFWaybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('equipment_initial', models.CharField(max_length=10)),
                ('equipment_number', models.CharField(max_length=20)),
                ('waybill_data', models.JSONField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BNSF Waybill',
                'verbose_name_plural': 'BNSF Waybills',
                'db_table': 'bnsf_waybills',
                'ordering': ['-processed_at'],
            },
        ),
    ]
