# Generated by Django 5.2.6 on 2025-09-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bnsfcertificate_bnsfwaybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnsfcertificate',
            name='cars_api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bnsfcertificate',
            name='waybill_api_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
